development:
      
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: fedena
  pool: 5
  username: root
  password: abcd
  host: localhost
      
test: &test
      host: localhost
      adapter: mysql
      database: fedena_two_new
      port: 3306
      username: root
      password: foradian

production:
      host: localhost
      adapter: mysql
      database: fedena2_1
      port: 3306
      username: root
      password: foradian
cucumber:
  <<: *test
